"""Embedding entity - represents a vector representation of a chunk."""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field, field_validator


class Embedding(BaseModel):
    """A vector representation of a chunk.

    Embeddings are generated by an embedding provider and stored in a vector database.
    """

    chunk_id: UUID = Field(..., description="Chunk this embedding represents")
    vector: list[float] = Field(..., description="Embedding vector")
    model: str = Field(..., description="Embedding model used")
    dimension: int = Field(..., gt=0, description="Vector dimension")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    @field_validator("vector")
    @classmethod
    def vector_not_empty(cls, v: list[float]) -> list[float]:
        if not v:
            raise ValueError("Embedding vector cannot be empty")
        return v

    @field_validator("dimension")
    @classmethod
    def dimension_matches_vector(cls, v: int, info: Any) -> int:
        if "vector" in info.data and v != len(info.data["vector"]):
            raise ValueError(f"Dimension {v} does not match vector length {len(info.data['vector'])}")
        return v
